server:
  port: 5050

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: myapp-service
          uri: lb:http://MYAPP-SERVICE
          predicates:
            - Path=/test/**
        - id: email-service
          uri: lb:http://EMAIL-SERVICE
          predicates:
            - Path=/email/**
